Correctly throw RemoteResourceNotFoundException
Aiven-Open/tiered-storage-for-apache-kafka pull request #378
Opened 2023-09-07 17:29 UTC by ivanyu

This commit makes `RemoteStorageManager` throw `RemoteResourceNotFoundException` on the fetch operation when the requested object (or the manifest object) is not found.

Closes #180

2023-09-13 04:18 UTC, jeqo approved these changes
LGTM

2023-09-27 08:29 UTC, AnatolyPopov requested changes

2023-09-27 08:31 UTC, AnatolyPopov commented on core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
> +    }
And same thing for other tests

2023-09-27 08:53 UTC, AnatolyPopov approved these changes
LGTM

2023-09-27 08:53 UTC, merged