fix: capture GCS metrics when bucket contains hyphens
Aiven-Open/tiered-storage-for-apache-kafka pull request #420
Opened 2023-10-12 15:07 UTC by jeqo

GCS bucket names can contain hyphens, underscores, dots, etc: https://cloud.google.com/storage/docs/buckets

Fixing the regex to match URLs, and a couple of minor related refactoring. See commits for details.

2023-10-12 15:16 UTC, jeqo commented
Weirdly enough, seems that the GCS Fake Server doesn't allow these characters on the bucket name, so I wasn't able to change the test; but tried it manually on our demo where it wasn't working.

2023-10-13 10:01 UTC, ivanyu requested changes
Thanks for catching!

2023-10-13 10:01 UTC, ivanyu commented on storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/MetricCollector.java
> +        Pattern.compile("^/storage/v1/b/(.*)/o/(.*)/?$");
I guess this would be more correct
```suggestion
        Pattern.compile("^/storage/v1/b/([^/]+)/o/([^/]+)/?$");
```

2023-10-13 10:27 UTC, jeqo commented
Thanks @ivanyu, suggestion makes sense. Adding a test case for the regex at least so we can validate the expressions.

2023-10-13 10:41 UTC, ivanyu approved these changes

2023-10-13 10:41 UTC, merged